name: CI/CD

on:
  push:
    tags:
      - v*

jobs:
  ci:
    name: Continuous Integrations
    uses: ./.github/workflows/ci.yml
  bin_release:
    name: Build and Release Binary
    needs: ci
    uses: ./.github/workflows/release.yml