on: workflow_call

jobs:
  send-webhook-signal:
    name: Send Webhook Signal
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
